### ISSUE TITLE
Export Library path

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/v4r_ros_wrappers#1]
Would need help for this: 
https://github.com/strands-project/v4r_ros_wrappers/blob/master/singleview_object_recognizer/CMakeLists.txt#L78

**Comment by marc-hanheide** [comment]
I think, you should set V4R up properly in cmake. In fact it should probably install its own cmake module, e.g. read http://www.cmake.org/Wiki/CMake/Tutorials/Packaging

You can set any variables in the V4R specific CMake module and simply use `find_package` in here and in any other repos that use V4R

**Comment by marc-hanheide** [comment]
That said, I found you already create a cmake module from [v4rConfig.cmake.in](https://github.com/strands-project/v4r/blob/master/v4rConfig.cmake.in) so you could just use that to set `V4R_DIR` correctly?
