### ISSUE TITLE
Problem in building recognition servie

### ISSUE THREAD

**Issue by jontromanab** [strands-project/v4r_ros_wrappers#13]
While I was building v4r_ros_wrapper by catkin_make this is the error message I received:

Linking CXX executable /root/catkin_ws/devel/lib/singleview_object_recognizer/recognition_service
CMakeFiles/recognition_service.dir/src/recognizer_ros.cpp.o: In function `v4r::SingleViewRecognizer::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> const>)':
/opt/ros/indigo/include/v4r/recognition/singleview_object_recognizer.h:328: undefined reference to`v4r::common::computeNormals(boost::shared_ptrpcl::PointCloud<pcl::PointXYZRGB const> const&, boost::shared_ptrpcl::PointCloud<pcl::Normal >&, int)'
/opt/ros/indigo/lib/libv4r_tomgine.so.1.0: undefined reference to `XGetXCBConnection'
collect2: error: ld returned 1 exit status
make[2]: **\* [/root/catkin_ws/devel/lib/singleview_object_recognizer/recognition_service] Error 1
make[1]: **\* [v4r_ros_wrappers/singleview_object_recognizer/CMakeFiles/recognition_service.dir/all] Error 2
make: **\* [all] Error 2

**Comment by jontromanab** [comment]
I figured out there was a problem with my v4r pacakge. Now I have installed the v4r-ros-wrapper directly from the repository also tried with git clone ....but everytime I am having the same error.

ERROR: cannot launch node of type [singleview_object_recognizer/recognition_service]: can't locate node [recognition_service] in package [singleview_object_recognizer]

Please can anybody help me?

**Comment by marc-hanheide** [comment]
Did you install V4R from the repositories? If so, it is none that version 1.0.10 is buggy (e.g. it does not contain the recognition module). @ToMadoRe is on it to fix it. See https://github.com/strands-project/v4r/pull/34 The next release should be working again. If it's urgent, I can re-release the 1.0.9.

**Comment by jontromanab** [comment]
Can you please re-release the version 1.0.9? That would be really nice.

I was trying to build the wrapper package without Tomgine. But now it is showing a new error.
/root/catkin_ws/src/v4r_ros_wrappers/camera_tracker/src/camera_tracker.cpp:44:47: fatal error: v4r/keypoints/impl/convertCloud.hpp: No such file or directory
 #include <v4r/keypoints/impl/convertCloud.hpp>
                                               ^
There is not file as such. 
Thank you for replying.

**Comment by marc-hanheide** [comment]
OK. I should be clearer. we can revert all changes in the main branch back to the 1.0.9 tag. before, we could branch the current HEAD for you to keep all changes just in case. Then we release 1.0.11 from the effectively same source as 1.0.9. Is that what you guys want @ToMadoRe? I wouldn't do it without you confirming. we meet tomorrow anyway...

**Comment by jontromanab** [comment]
OHo...I did not realize that would be so much trouble. If it bothers you guys, then I can wait for the new version.

**Comment by marc-hanheide** [comment]
not too much hassle, I just really am not the person to decide these things ;-)

**Comment by jontromanab** [comment]
So can you please send me the link where I can get the 1.0.9 version?

**Comment by marc-hanheide** [comment]
we have just release V4R 1.0.11 which should work again. just update. the ros wrappers however still needs some love.

**Comment by jontromanab** [comment]
Thank you very much. I would love to contribute in the package if there is any option to do so. Please let me know if I can be of any help. I am a Phd student and my research is focused on object recognition using 3d.

**Comment by jontromanab** [comment]
I am extremely sorry.....But my v4r-ros-wrapper is still not building.
The new v4r is building fine. But when trying to build the v4r-ros-wrapper, its seem that these three files are missing.
#include <v4r/keypoints/impl/convertCloud.hpp>
 #include <v4r/tomgine/tgTomGineThread.h>
#include <v4r/recognition/multiview_object_recognizer_service.h>

**Comment by jontromanab** [comment]
I am extremely sorry.....But my v4r-ros-wrapper is still not building.
The new v4r is building fine. But when trying to build the v4r-ros-wrapper, its seem that these three files are missing.
 #include <v4r/keypoints/impl/convertCloud.hpp>
 #include <v4r/tomgine/tgTomGineThread.h>
 #include <v4r/recognition/multiview_object_recognizer_service.h>

**Comment by jontromanab** [comment]
I am extremely sorry.....But my v4r-ros-wrapper is still not building.
The new v4r is building fine. But when trying to build the v4r-ros-wrapper, its seem that these three files are missing.
#include<v4r/keypoints/impl/covertCloud.hpp>
#include<v4r/timgine/tgTomGineThread.h>
#include<v4r/recognition/multiview_object_recognizer_service.h>

**Comment by jontromanab** [comment]
I am extremely sorry.....But my v4r-ros-wrapper is still not building.
The new v4r is building fine. But when trying to build the v4r-ros-wrapper, its seem that these three files are missing.
fatal error: v4r/keypoints/impl/convertCloud.hpp: No such file or directory
 #include <v4r/keypoints/impl/convertCloud.hpp>

/root/v4r/modules/recognition/include/v4r/recognition/mesh_source.h:23:41: fatal error: v4r/tomgine/tgTomGineThread.h: No such file or directory
 #include <v4r/tomgine/tgTomGineThread.h>

/root/catkin_ws/src/v4r_ros_wrappers/multiview_object_recognizer/include/multiview_object_recognizer_ros.h:1:65: fatal error: v4r/recognition/multiview_object_recognizer_service.h: No such file or directory
 #include <v4r/recognition/multiview_object_recognizer_service.h>

**Comment by marc-hanheide** [comment]
Hang on... are you building both V4R and V4R_ros_wrappers form source? Or are you using the Debian packages? If you are building, then you could just download a [V4R 1.0.9 tar ball](https://github.com/strands-project/v4r/releases/tag/1.0.9) and a [V4R_ros_wrappers 0.0.5 tar ball](https://github.com/strands-project/v4r_ros_wrappers/releases/tag/0.0.5) and compile it, right? Or, you wait another day or two, when @ToMadoRe will likely have fixed the ros wrappers.

**Comment by jontromanab** [comment]
I was trying to build both of them from sources. I have already tried the v4r 1.0.9 version. But it was showing errors with the tomgine package and also with the version of v4r_ros_wrapper

**Comment by marc-hanheide** [comment]
Alright... it should all be fixed now (fingers crossed). V4R 1.0.11 and V4R_ros_wrappers 0.0.6 should be working again, and also Ubuntu packages should be available shortly.

**Comment by marc-hanheide** [comment]
see https://github.com/strands-project/v4r_ros_wrappers/pull/14 I expect this to be now working, so if it still is a problem, please reopen.
